### ISSUE TITLE
Turn the sources into UDL )

### ISSUE THREAD

**Issue by evshvarov** [aless80/DeepSeeButtons#1]
Like any of[ these projects](https://github.com/topics/cacheobjectscript-udl) )

**Comment by aless80** [comment]
Thank you, I exported all files using UDL formatting for the following projects:

DeepSee-USNames
DeepSee-Erdbeben
DeepSeeButtons
DeepSee_TimeCharts

 I still keep the old .xml files for compatibility with older versions on Caché

**Comment by aless80** [comment]
and i just created 
Install-Samples-BI

**Comment by evshvarov** [comment]
Thanks!
